In [42]:
import pandas as pd

df = pd.read_csv("data.csv")
df.sample(5)

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
5171,0,0.459660,0.483864,0.494673,0.616757,0.616700,0.998820,0.797175,0.809078,0.303462,...,0.766856,0.000493,0.623681,0.616752,0.837722,0.279550,0.026710,0.564741,1,0.030113
1149,0,0.410276,0.467455,0.457412,0.605630,0.605630,0.998929,0.797097,0.809040,0.303097,...,0.752335,0.014536,0.623780,0.605627,0.833008,0.291304,0.026671,0.564511,1,0.016055
5747,0,0.504461,0.568524,0.553135,0.601587,0.601587,0.999036,0.797474,0.809380,0.303531,...,0.817955,0.003016,0.624251,0.601584,0.841611,0.278351,0.026796,0.565182,1,0.036611
6603,0,0.597719,0.629252,0.629370,0.653988,0.653988,0.999318,0.797794,0.809610,0.303501,...,0.852901,0.001194,0.623951,0.653988,0.843364,0.276477,0.026792,0.565163,1,0.064141
5269,0,0.521328,0.573157,0.565501,0.609197,0.609738,0.999019,0.797457,0.809365,0.303538,...,0.816896,0.001478,0.623874,0.609198,0.842191,0.282862,0.026791,0.565158,1,0.022065

In [43]:
df.shape

(6819, 96)

In [44]:
df.columns

Index(['Bankrupt?', ' ROA(C) before interest and depreciation before interest',
       ' ROA(A) before interest and % after tax',
       ' ROA(B) before interest and depreciation after tax',
       ' Operating Gross Margin', ' Realized Sales Gross Margin',
       ' Operating Profit Rate', ' Pre-tax net Interest Rate',
       ' After-tax net Interest Rate',
       ' Non-industry income and expenditure/revenue',
       ' Continuous interest rate (after tax)', ' Operating Expense Rate',
       ' Research and development expense rate', ' Cash flow rate',
       ' Interest-bearing debt interest rate', ' Tax rate (A)',
       ' Net Value Per Share (B)', ' Net Value Per Share (A)',
       ' Net Value Per Share (C)', ' Persistent EPS in the Last Four Seasons',
       ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)',
       ' Operating Profit Per Share (Yuan ¥)',
       ' Per Share Net profit before tax (Yuan ¥)',
       ' Realized Sales Gross Profit Growth Rate',
       ' Operating Profit Growth Rate', ' After-tax Net Profit Growth Rate',
       ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate',
       ' Total Asset Growth Rate', ' Net Value Growth Rate',
       ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %',
       ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio',
       ' Total debt/Total net worth', ' Debt ratio %', ' Net worth/Assets',
       ' Long-term fund suitability ratio (A)', ' Borrowing dependency',
       ' Contingent liabilities/Net worth',
       ' Operating profit/Paid-in capital',
       ' Net profit before tax/Paid-in capital',
       ' Inventory and accounts receivable/Net value', ' Total Asset Turnover',
       ' Accounts Receivable Turnover', ' Average Collection Days',
       ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency',
       ' Net Worth Turnover Rate (times)', ' Revenue per person',
       ' Operating profit per person', ' Allocation rate per person',
       ' Working Capital to Total Assets', ' Quick Assets/Total Assets',
       ' Current Assets/Total Assets', ' Cash/Total Assets',
       ' Quick Assets/Current Liability', ' Cash/Current Liability',
       ' Current Liability to Assets', ' Operating Funds to Liability',
       ' Inventory/Working Capital', ' Inventory/Current Liability',
       ' Current Liabilities/Liability', ' Working Capital/Equity',
       ' Current Liabilities/Equity', ' Long-term Liability to Current Assets',
       ' Retained Earnings to Total Assets', ' Total income/Total expense',
       ' Total expense/Assets', ' Current Asset Turnover Rate',
       ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate',
       ' Cash Turnover Rate', ' Cash Flow to Sales', ' Fixed Assets to Assets',
       ' Current Liability to Liability', ' Current Liability to Equity',
       ' Equity to Long-term Liability', ' Cash Flow to Total Assets',
       ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity',
       ' Current Liability to Current Assets', ' Liability-Assets Flag',
       ' Net Income to Total Assets', ' Total assets to GNP price',
       ' No-credit Interval', ' Gross Profit to Sales',
       ' Net Income to Stockholder's Equity', ' Liability to Equity',
       ' Degree of Financial Leverage (DFL)',
       ' Interest Coverage Ratio (Interest expense to EBIT)',
       ' Net Income Flag', ' Equity to Liability'],
      dtype='object')

In [45]:
df.describe()

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
count,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,...,6819.000000,6.819000e+03,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.000000,6819.0,6819.000000
mean,0.032263,0.505180,0.558625,0.553589,0.607948,0.607929,0.998755,0.797190,0.809084,0.303623,...,0.807760,1.862942e+07,0.623915,0.607946,0.840402,0.280365,0.027541,0.565358,1.0,0.047578
std,0.176710,0.060686,0.065620,0.061595,0.016934,0.016916,0.013010,0.012869,0.013601,0.011163,...,0.040332,3.764501e+08,0.012290,0.016934,0.014523,0.014463,0.015668,0.013214,0.0,0.050014
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.0,0.000000
25%,0.000000,0.476527,0.535543,0.527277,0.600445,0.600434,0.998969,0.797386,0.809312,0.303466,...,0.796750,9.036205e-04,0.623636,0.600443,0.840115,0.276944,0.026791,0.565158,1.0,0.024477
50%,0.000000,0.502706,0.559802,0.552278,0.605997,0.605976,0.999022,0.797464,0.809375,0.303525,...,0.810619,2.085213e-03,0.623879,0.605998,0.841179,0.278778,0.026808,0.565252,1.0,0.033798
75%,0.000000,0.535563,0.589157,0.584105,0.613914,0.613842,0.999095,0.797579,0.809469,0.303585,...,0.826455,5.269777e-03,0.624168,0.613913,0.842357,0.281449,0.026913,0.565725,1.0,0.052838
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,9.820000e+09,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000

In [46]:
df.isnull().sum()

Bankrupt?                                                   0
 ROA(C) before interest and depreciation before interest    0
 ROA(A) before interest and % after tax                     0
 ROA(B) before interest and depreciation after tax          0
 Operating Gross Margin                                     0
                                                           ..
 Liability to Equity                                        0
 Degree of Financial Leverage (DFL)                         0
 Interest Coverage Ratio (Interest expense to EBIT)         0
 Net Income Flag                                            0
 Equity to Liability                                        0
Length: 96, dtype: int64

In [47]:
print(df['Bankrupt?'].value_counts())
print(df['Bankrupt?'].value_counts(normalize=True))

Bankrupt?
0    6599
1     220
Name: count, dtype: int64
Bankrupt?
0    0.967737
1    0.032263
Name: proportion, dtype: float64

Dataset is highly imbalanced. 96.8 percent of companies doesnt go bankrupt  only 3.2% get bankrupt.

In [48]:
print(df.duplicated().sum())

0

In [49]:
df.corr()['Bankrupt?']

Bankrupt?                                                   1.000000
 ROA(C) before interest and depreciation before interest   -0.260807
 ROA(A) before interest and % after tax                    -0.282941
 ROA(B) before interest and depreciation after tax         -0.273051
 Operating Gross Margin                                    -0.100043
                                                              ...
 Liability to Equity                                        0.166812
 Degree of Financial Leverage (DFL)                         0.010508
 Interest Coverage Ratio (Interest expense to EBIT)        -0.005509
 Net Income Flag                                                 NaN
 Equity to Liability                                       -0.083048
Name: Bankrupt?, Length: 96, dtype: float64

In [50]:
df = df.drop(columns=[' Net Income Flag'],axis=0)

In [51]:

corr_matrix=df.corr()
corr_table =corr_matrix.unstack().reset_index()
corr_table.columns = ['Feature 1', 'Feature 2', 'Correlation']
corr_table = corr_table[corr_table['Feature 1'] != corr_table['Feature 2']]
corr_table['Abs_Corr'] = corr_table['Correlation'].abs()
strong_pairs = corr_table.sort_values(by='Abs_Corr', ascending=False).drop_duplicates(subset=['Correlation'])

print(strong_pairs[['Feature 1', 'Feature 2', 'Correlation']].head(10))

                              Feature 1                             Feature 2  \
6348         Current Liabilities/Equity           Current Liability to Equity
3553                       Debt ratio %                      Net worth/Assets
469              Operating Gross Margin                 Gross Profit to Sales
1633            Net Value Per Share (A)               Net Value Per Share (C)
385              Operating Gross Margin           Realized Sales Gross Margin
8460              Gross Profit to Sales           Realized Sales Gross Margin
1631            Net Value Per Share (A)               Net Value Per Share (B)
1726            Net Value Per Share (C)               Net Value Per Share (B)
4012   Operating profit/Paid-in capital   Operating Profit Per Share (Yuan ¥)
2591     Regular Net Profit Growth Rate      After-tax Net Profit Growth Rate

      Correlation
6348     1.000000
3553    -1.000000
469      1.000000
1633     0.999837
385      0.999518
8460     0.999518
1631     0.999342
1726     0.999179
4012     0.998696
2591     0.996186

In [ ]:
#Dimensionality reduction (dropping one of the features from the strong pairs)
threshold = 0.90
features_to_drop = set()

for index, row in strong_pairs.iterrows():
    f1 = row['Feature 1']
    f2 = row['Feature 2']
    corr = row['Abs_Corr']
    
    if corr > threshold:
        if f1 not in features_to_drop:
            features_to_drop.add(f2)

print(f"Identified {len(features_to_drop)} redundant features for removal.")
df = df.drop(columns=list(features_to_drop))

Identified 18 redundant features for removal.
['Bankrupt?', ' ROA(A) before interest and % after tax', ' Operating Gross Margin', ' Operating Profit Rate', ' Non-industry income and expenditure/revenue', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (A)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Fixed Assets to Assets', ' Current Liability to Liability', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Liability-Assets Flag', ' Total assets to GNP price', ' No-credit Interval', " Net Income to Stockholder's Equity", ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']

In [53]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['Bankrupt?'])
y = df['Bankrupt?']
#STRATIFY=y is mandatory here It ensures both sets get exactly 3% bankruptcies
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
print(f"Training Features Shape: {X_train.shape}")
print(f"Testing Features Shape: {X_test.shape}")
print(f"Bankrupt companies in Training Set: {y_train.sum()}")
print(f"Bankrupt companies in Testing Set: {y_test.sum()}")

Training Features Shape: (5455, 76)
Testing Features Shape: (1364, 76)
Bankrupt companies in Training Set: 176
Bankrupt companies in Testing Set: 44

In [ ]:
import xgboost as xgb
from sklearn.metrics import classification_report, accuracy_score
import pickle

def train_and_eval(X_train, y_train, X_test, y_test, label):
    # Calculate imbalance weight
    imbalance_weight = (y_train == 0).sum() / (y_train == 1).sum()
    
    model = xgb.XGBClassifier(
        scale_pos_weight=imbalance_weight,
        random_state=42,
        eval_metric='logloss',
        max_depth=6,
        learning_rate=0.05,
        n_estimators=1000,
        early_stopping_rounds=50
    )
    
    model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)
    preds = model.predict(X_test)

    
    print(f"\n--- {label} Performance ---")
    print(f"Accuracy: {accuracy_score(y_test, preds):.4f}")
    print(classification_report(y_test, preds))
    return model

print("Training Baseline...")
model_baseline = train_and_eval(X_train, y_train, X_test, y_test, "Baseline")

importances = model_baseline.feature_importances_
feature_importance_df = pd.DataFrame({'Feature': X_train.columns, 'Importance': importances})
useless_features = feature_importance_df[feature_importance_df['Importance'] == 0]['Feature'].tolist()

print(f"\nIdentified {len(useless_features)} useless features to drop.")
X_train_refined = X_train.drop(columns=useless_features)
X_test_refined = X_test[X_train_refined.columns] # Sync columns

print("\nTraining Refined Model...")
model_refined = train_and_eval(X_train_refined, y_train, X_test_refined, y_test, "Refined")

Training Baseline...

--- Baseline Performance ---
Accuracy: 0.9670
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1320
           1       0.49      0.55      0.52        44

    accuracy                           0.97      1364
   macro avg       0.74      0.76      0.75      1364
weighted avg       0.97      0.97      0.97      1364


Identified 2 useless features to drop.
[' ROA(A) before interest and % after tax', ' Operating Gross Margin', ' Operating Profit Rate', ' Non-industry income and expenditure/revenue', ' Operating Expense Rate', ' Research and development expense rate', ' Cash flow rate', ' Interest-bearing debt interest rate', ' Tax rate (A)', ' Net Value Per Share (A)', ' Persistent EPS in the Last Four Seasons', ' Cash Flow Per Share', ' Revenue Per Share (Yuan ¥)', ' Realized Sales Gross Profit Growth Rate', ' Operating Profit Growth Rate', ' Regular Net Profit Growth Rate', ' Continuous Net Profit Growth Rate', ' Total Asset Growth Rate', ' Net Value Growth Rate', ' Total Asset Return Growth Rate Ratio', ' Cash Reinvestment %', ' Current Ratio', ' Quick Ratio', ' Interest Expense Ratio', ' Total debt/Total net worth', ' Debt ratio %', ' Long-term fund suitability ratio (A)', ' Borrowing dependency', ' Contingent liabilities/Net worth', ' Operating profit/Paid-in capital', ' Inventory and accounts receivable/Net value', ' Total Asset Turnover', ' Accounts Receivable Turnover', ' Average Collection Days', ' Inventory Turnover Rate (times)', ' Fixed Assets Turnover Frequency', ' Net Worth Turnover Rate (times)', ' Revenue per person', ' Operating profit per person', ' Allocation rate per person', ' Working Capital to Total Assets', ' Quick Assets/Total Assets', ' Current Assets/Total Assets', ' Cash/Total Assets', ' Quick Assets/Current Liability', ' Cash/Current Liability', ' Current Liability to Assets', ' Operating Funds to Liability', ' Inventory/Working Capital', ' Inventory/Current Liability', ' Current Liabilities/Liability', ' Working Capital/Equity', ' Current Liabilities/Equity', ' Long-term Liability to Current Assets', ' Retained Earnings to Total Assets', ' Total income/Total expense', ' Total expense/Assets', ' Current Asset Turnover Rate', ' Quick Asset Turnover Rate', ' Working capitcal Turnover Rate', ' Cash Turnover Rate', ' Fixed Assets to Assets', ' Equity to Long-term Liability', ' Cash Flow to Total Assets', ' Cash Flow to Liability', ' CFO to Assets', ' Cash Flow to Equity', ' Current Liability to Current Assets', ' Total assets to GNP price', ' No-credit Interval', " Net Income to Stockholder's Equity", ' Degree of Financial Leverage (DFL)', ' Interest Coverage Ratio (Interest expense to EBIT)', ' Equity to Liability']

Training Refined Model...

--- Refined Performance ---
Accuracy: 0.9670
              precision    recall  f1-score   support

           0       0.98      0.98      0.98      1320
           1       0.49      0.55      0.52        44

    accuracy                           0.97      1364
   macro avg       0.74      0.76      0.75      1364
weighted avg       0.97      0.97      0.97      1364


Refined model saved successfully!